services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped

    ports:
      - "8096:8096"

    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000

    volumes:
      - ./config:/config
      - ./cache:/cache
      - /mnt/data/media/jellyfin:/media

    devices:
      - /dev/dri:/dev/dri

    labels:
      - traefik.enable=true

      - traefik.http.routers.jellyfin.rule=Host(`jellyfin.lan`)
      - traefik.http.routers.jellyfin.entrypoints=websecure
      - traefik.http.routers.jellyfin.tls=true

      - traefik.http.services.jellyfin.loadbalancer.server.port=8096

networks:
  proxy:
    external: true
