FROM nextcloud:apache

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        ffmpeg \
        exiftool \
        libheif-examples \
        imagemagick && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
