services:
  db:
    image: mariadb:11-noble
    container_name: nextcloud-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - nextcloud-db:/var/lib/mysql
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD-SHELL", "mariadb-admin ping -h localhost -u root -p$${MARIADB_ROOT_PASSWORD} --silent"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: always
    volumes:
      - ./redis-data:/data:/data
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 3
  app:
    build:
      context: .
    container_name: nextcloud
    restart: always
    ports:
      - "8080:80"
    devices:
      - /dev/dri:/dev/dri

    group_add:
      - "992"
    volumes:
      - nextcloud-data:/var/www/html
      - /mnt/data/nextcloud:/var/www/html/data
    environment:
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: db
      # Nextcloud läuft hinter Traefik
      OVERWRITEPROTOCOL: https
      OVERWRITEHOST: nc.node-forge.eu
      OVERWRITECLIURL: https://nc.node-forge.eu
      TRUSTED_PROXIES: 192.168.178.74
      NEXTCLOUD_TRUSTED_DOMAINS: "localhost 192.168.178.69 nc.lan nc.node-forge.eu"

      # Redis-Passwort an Nextcloud weitergeben
      REDIS_HOST: redis
      REDIS_HOST_PASSWORD: ${REDIS_PASSWORD}
    depends_on:
      - db
      - redis
    networks:
      - nextcloud-net
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost/status.php"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
volumes:
  nextcloud-data:
  nextcloud-db:

networks:
  nextcloud-net:
    driver: bridge
